# Generated by Django 5.1 on 2024-09-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_reguser2_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=25, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('firstname', models.CharField(max_length=25, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='День рождения')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='RegUser1',
        ),
        migrations.DeleteModel(
            name='RegUser2',
        ),
    ]
