# Generated by Django 5.1.1 on 2024-10-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reguser_groups_reguser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
