# Generated by Django 5.1 on 2024-09-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_reguser_options_remove_reguser_login_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reguser',
            options={},
        ),
        migrations.RemoveField(
            model_name='reguser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='reguser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='reguser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='reguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='firstname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
    ]
