# Generated by Django 5.1 on 2024-09-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_reguser_options_remove_reguser_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reguser',
            old_name='birthday',
            new_name='birthdate',
        ),
    ]
